#!/usr/bin/env python3

import sys
import rclpy
from rclpy.node import Node
from code_profiler.msg import Statistics

import numpy


class LiveProfile(Node):

    agg_length = 1  # seconds

    agg = {}
    start_agg = None

    def __init__(self):
        super().__init__('liveprofile')

        args = sys.argv
        if len(args) < 2:
            self.get_logger().error(f'usage: {args[0]} topicname')
            sys.exit(1)

        self.start_agg = self.get_clock().now()
        self.subscription = self.create_subscription(
            Statistics,
            args[1],
            self.callback,
            10)

    def callback(self, data):
        now = self.get_clock().now()
        diff = (now - self.start_agg).nanoseconds / 1e9  # Convert to seconds
        if diff > self.agg_length:
            self.report(self.agg)
            self.start_agg = now
            self.agg = {}
        else:
            for l, t in zip(data.labels, data.time_secs):
                if l not in self.agg:
                    self.agg[l] = []
                self.agg[l].append(t)

    def report(self, data):
        for k, v in sorted(data.items()):
            mean = "{0:.3f} ms".format(numpy.mean(v, axis=0)*1000)
            std  = "{0:.3f} ms".format(numpy.std(v, axis=0)*1000)
            print(f'{k:<55}\tmean={mean}\tstd={std}\t({len(v)} samples)')


if __name__ == '__main__':
    rclpy.init()
    profiler = LiveProfile()
    rclpy.spin(profiler)
    profiler.destroy_node()
    rclpy.shutdown()
